[Log]
Output = "stream"

[Server]
PortNum  = 8080
HostName = "localhost:8080"

[DB]
UserID     = "root"
Password   = "root"
HostName   = "127.0.0.1"
PortNumber = "3306"
Name       = "squidgirl"

[LoginConfig]
PassSalt   = "1uwnxGUW71XMMeqABZnC41Bnh59L7E9k0aUK6T7C"
TokenSalt  = "Zzt5mfGTDYmFcGEYUzBbcPRqUUPR9Bdr7SJwWSxh"

